import uuid
from datetime import datetime
from celery import chain
from app.celery_app import celery_app
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from sqlalchemy.orm import Session

from app.core.deps import require_role
from app.db import get_db
from app.models.document import Document
from app.models.document_chunk import DocumentChunk
from app.services.storage_service import upload_file
from app.services.text_processing_service import extract_text, chunk_text
from app.tasks.ingestion import (
    embed_course_task,
    generate_sanity_mcqs_task,
    generate_mcqs_task,
)

router = APIRouter(
    prefix="/documents",
    tags=["Documents"],
)


@router.post("/upload")
def upload_document(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    user=Depends(require_role("trainer", "admin")),
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="A file must be uploaded",
        )

    document_id = f"document_{uuid.uuid4().hex[:12]}"

    document = Document(
        document_id=document_id,
        filename=file.filename,
        uploaded_by=user.id,
        status="sanity_pending",
    )

    db.add(document)

    try:
        extracted_text = extract_text(file.file, file.filename)
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e),
        )

    file.file.seek(0)

    object_name = f"{document_id}/{file.filename}"

    upload_file(
        file.file,
        object_name,
        file.content_type or "application/octet-stream",
    )

    chunks = chunk_text(extracted_text)

    if not chunks:
        raise HTTPException(
            status_code=400,
            detail="No text could be extracted from the uploaded document",
        )

    for index, chunk in enumerate(chunks):
        document_chunk = DocumentChunk(
            chunk_id=f"chunk_{uuid.uuid4().hex[:12]}",
            parent_doc_id=document_id,
            chunk_text=chunk,
            chunk_order=index,
            page_ref=None,
            embedding=None,
        )

        db.add(document_chunk)

    db.commit()

    task = chain(
    embed_course_task.s(document_id),
    generate_sanity_mcqs_task.si(document_id),
).apply_async()

    return {
        "message": "Document uploaded and sanity check generation queued successfully",
        "document_id": document_id,
        "filename": file.filename,
        "file_path": object_name,
        "chunks_created": len(chunks),
        "task_id": task.id,
        "task_status": "queued",
        "uploaded_by": user.id,
    }
@router.get("/sanity-preview/{task_id}")
def get_sanity_preview(
    task_id: str,
    user=Depends(require_role("trainer", "admin")),
):
    """
    Return the temporary sanity-check MCQs generated by Celery.

    These MCQs are not stored in the production mcqs table.
    """

    task = celery_app.AsyncResult(task_id)

    if task.state == "PENDING":
        return {
            "status": "pending",
            "message": "Sanity-check MCQs are still being generated.",
        }

    if task.state == "STARTED":
        return {
            "status": "processing",
            "message": "Sanity-check MCQs are currently being generated.",
        }

    if task.state == "FAILURE":
        raise HTTPException(
            status_code=500,
            detail="Sanity-check MCQ generation failed.",
        )

    if task.state != "SUCCESS":
        return {
            "status": task.state.lower(),
            "message": "Sanity-check generation is not yet complete.",
        }

    result = task.result

    return {
        "status": "completed",
        "document_id": result.get("doc_id"),
        "message": result.get("message"),
        "samples": result.get("samples", []),
        "sample_count": len(result.get("samples", [])),
    }
@router.post("/{document_id}/approve")

def approve_document(
    document_id: str,
    db: Session = Depends(get_db),
    user=Depends(require_role("trainer", "admin")),
):
    """
    Approve the sanity-check stage for a document.

    Only a document in sanity_pending state can be approved.
    """

    document = (
        db.query(Document)
        .filter(Document.document_id == document_id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found.",
        )

    if document.status != "sanity_pending":
        raise HTTPException(
            status_code=400,
            detail=f"Document cannot be approved from status '{document.status}'.",
        )

    from datetime import datetime

    document.status = "sanity_approved"
    document.approved_at = datetime.utcnow()

    db.commit()
    db.refresh(document)

    task = generate_mcqs_task.delay(document.document_id)

    return {
    "message": "Document sanity check approved and MCQ generation queued.",
    "document_id": document.document_id,
    "status": document.status,
    "approved_at": document.approved_at,
    "approved_by": user.id,
    "task_id": task.id,
    "task_status": "queued",
}
@router.post("/{document_id}/reject")
def reject_document(
    document_id: str,
    db: Session = Depends(get_db),
    user=Depends(require_role("trainer", "admin")),
):
    """
    Reject the sanity-check stage for a document.

    Rejected documents cannot proceed to concept extraction.
    """

    document = (
        db.query(Document)
        .filter(Document.document_id == document_id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found.",
        )

    if document.status != "sanity_pending":
        raise HTTPException(
            status_code=400,
            detail=f"Document cannot be rejected from status '{document.status}'.",
        )

    document.status = "sanity_rejected"

    db.commit()
    db.refresh(document)

    return {
        "message": "Document sanity check rejected.",
        "document_id": document.document_id,
        "status": document.status,
        "rejected_by": user.id,
    }