"""add concept_review_queue and mcq_generation_log tables

Revision ID: 071653280ffc
Revises: 8289b3c1c336
Create Date: 2026-09-05 15:23:40.100223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071653280ffc'
down_revision: Union[str, Sequence[str], None] = '8289b3c1c336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcq_generation_log',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('concepts_found', sa.Integer(), nullable=True),
    sa.Column('mcqs_generated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('concept_review_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_concept_name', sa.String(), nullable=False),
    sa.Column('suggested_domain', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.String(), nullable=False),
    sa.Column('best_match_concept_id', sa.String(), nullable=True),
    sa.Column('best_match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_canonical_concept_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['best_match_concept_id'], ['concept_taxonomy.canonical_concept_id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.chunk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_concept_taxonomy_embedding'), table_name='concept_taxonomy', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_courses_embedding'), table_name='courses', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_document_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_document_chunks_parent_doc'), table_name='document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_document_chunks_parent_doc'), 'document_chunks', ['parent_doc_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_courses_embedding'), 'courses', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_concept_taxonomy_embedding'), 'concept_taxonomy', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('concept_review_queue')
    op.drop_table('mcq_generation_log')
    # ### end Alembic commands ###
