"""add assessment_history, concept_mastery

Revision ID: 3fef5d741ced
Revises: b6f4a0c9e2d1
Create Date: 2026-09-05 10:26:24.135882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fef5d741ced'
down_revision: Union[str, Sequence[str], None] = 'b6f4a0c9e2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
