"""add employee_profile, mcqs, competency_framework_matrix

Revision ID: 75b5e64aa407
Revises: f37abc50d2da
Create Date: 2026-09-05 10:12:05.123885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75b5e64aa407'
down_revision: Union[str, Sequence[str], None] = 'f37abc50d2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_framework_matrix',
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('competency_domain', sa.String(), nullable=False),
    sa.Column('expected_proficiency_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('designation', 'competency_domain')
    )
    op.create_table('employee_profile',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('years_of_service', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('concept_mastery',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('p_l0', sa.Float(), nullable=False),
    sa.Column('p_t', sa.Float(), nullable=False),
    sa.Column('p_g', sa.Float(), nullable=False),
    sa.Column('p_s', sa.Float(), nullable=False),
    sa.Column('p_mastery_current', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_taxonomy.canonical_concept_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'concept_id')
    )
    op.create_table('employee_training_history',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'course_id')
    )
    op.create_table('mcqs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option_id', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_taxonomy.canonical_concept_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('mcq_id', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_taxonomy.canonical_concept_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profile.employee_id'], ),
    sa.ForeignKeyConstraint(['mcq_id'], ['mcqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_history_session_id'), 'assessment_history', ['session_id'], unique=False)
    op.drop_index(op.f('idx_concept_taxonomy_embedding'), table_name='concept_taxonomy', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_courses_embedding'), table_name='courses', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_document_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_document_chunks_parent_doc'), table_name='document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_document_chunks_parent_doc'), 'document_chunks', ['parent_doc_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_courses_embedding'), 'courses', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_concept_taxonomy_embedding'), 'concept_taxonomy', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_assessment_history_session_id'), table_name='assessment_history')
    op.drop_table('assessment_history')
    op.drop_table('mcqs')
    op.drop_table('employee_training_history')
    op.drop_table('concept_mastery')
    op.drop_table('employee_profile')
    op.drop_table('competency_framework_matrix')
    # ### end Alembic commands ###
