"""add source_chunk_id, explanation, confidence_score to mcqs; add concept_review_queue and mcq_generation_log tables

Revision ID: 8289b3c1c336
Revises: c0a870727ad1
Create Date: 2026-09-05 15:17:56.945024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8289b3c1c336'
down_revision: Union[str, Sequence[str], None] = 'c0a870727ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('mcqs', sa.Column('source_chunk_id', sa.String(), nullable=True))
    op.add_column('mcqs', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('mcqs', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'mcqs', 'document_chunks', ['source_chunk_id'], ['chunk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcqs', type_='foreignkey')
    op.drop_column('mcqs', 'confidence_score')
    op.drop_column('mcqs', 'explanation')
    op.drop_column('mcqs', 'source_chunk_id')
   
    # ### end Alembic commands ###
