"""
Seed test data for the BKT pipeline.

This script uses three real concepts already loaded into concept_taxonomy
by the embedding pipeline.

Concepts used:
  - CC-0021: Data collection method
  - CC-0022: Data Validation
  - CC-0026: Documentation on methodology

For each concept, the script creates:
  - 5 live MCQs
  - Multiple difficulty levels
  - Test employees
  - Competency framework mappings

BKT's MCQ bank health check requires:
  - At least 5 live MCQs per concept
  - At least 2 distinct difficulty levels

Safe to re-run:
  - Existing employees, matrix rows, and MCQs are skipped.
  - Existing concepts are never modified or deleted.

Run from the repo root:

    python scripts/seed_bkt_test_data.py
"""

from app.db import SessionLocal
from app.models.concept import ConceptTaxonomy
from app.models.employee_profile import EmployeeProfile
from app.models.competency_matrix import CompetencyFrameworkMatrix
from app.models.mcq import MCQ


# ---------------------------------------------------------------------------
# 1. REAL CONCEPTS
# ---------------------------------------------------------------------------

# These concepts already exist in the real concept taxonomy and have
# embeddings generated by app/embed_and_load.py.

BKT_TEST_CONCEPT_IDS = [
    "CC-0021",  # Data collection method
    "CC-0022",  # Data Validation
    "CC-0026",  # Documentation on methodology
]


# ---------------------------------------------------------------------------
# 2. TEST EMPLOYEES
# ---------------------------------------------------------------------------

TEST_EMPLOYEES = [
    {
        "employee_id": "emp_test_001",
        "name": "Test Employee One",
        "designation": "Software Engineer",
        "years_of_service": 2,
        "department": "Engineering",
    },
    {
        "employee_id": "emp_test_002",
        "name": "Test Employee Two",
        "designation": "Compliance Officer",
        "years_of_service": 5,
        "department": "Legal & Compliance",
    },
]


# ---------------------------------------------------------------------------
# 3. COMPETENCY FRAMEWORK MATRIX
# ---------------------------------------------------------------------------
#
# IMPORTANT:
# competency_domain MUST exactly match the competency_area values
# in concept_taxonomy.
#
# Real values:
#
# CC-0021 -> Data Collection
# CC-0022 -> Metadata / Data Quality
# CC-0026 -> Data Quality / Methodology
#
# Expected proficiency level:
#   1 = beginner
#   5 = advanced
# ---------------------------------------------------------------------------

COMPETENCY_MATRIX_ROWS = [
    # Software Engineer
    {
        "designation": "Software Engineer",
        "competency_domain": "Data Collection",
        "expected_proficiency_level": 4,
    },
    {
        "designation": "Software Engineer",
        "competency_domain": "Metadata / Data Quality",
        "expected_proficiency_level": 4,
    },
    {
        "designation": "Software Engineer",
        "competency_domain": "Data Quality / Methodology",
        "expected_proficiency_level": 3,
    },

    # Compliance Officer
    {
        "designation": "Compliance Officer",
        "competency_domain": "Data Collection",
        "expected_proficiency_level": 3,
    },
    {
        "designation": "Compliance Officer",
        "competency_domain": "Metadata / Data Quality",
        "expected_proficiency_level": 4,
    },
    {
        "designation": "Compliance Officer",
        "competency_domain": "Data Quality / Methodology",
        "expected_proficiency_level": 5,
    },
]


# ---------------------------------------------------------------------------
# 4. MCQ HELPERS
# ---------------------------------------------------------------------------

def _opts(*texts):
    """Create four MCQ options with IDs a, b, c, d."""
    letters = "abcd"
    return [
        {"id": letters[i], "text": text}
        for i, text in enumerate(texts)
    ]


# ---------------------------------------------------------------------------
# 5. MCQs FOR REAL CONCEPTS
# ---------------------------------------------------------------------------
#
# Each concept has:
#   - 2 easy
#   - 2 medium
#   - 1 hard
#
# Total = 5 MCQs per concept.
# ---------------------------------------------------------------------------

MCQS_BY_CONCEPT = {

    # -----------------------------------------------------------------------
    # CC-0021: Data collection method
    # -----------------------------------------------------------------------

    "CC-0021": [
        {
            "id": "mcq_dc_001",
            "difficulty": "easy",
            "options": _opts(
                "Choosing a method for obtaining required data",
                "Deleting old database records",
                "Formatting a computer",
                "Compressing a file",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dc_002",
            "difficulty": "easy",
            "options": _opts(
                "Survey",
                "Database index",
                "Source code compiler",
                "Encryption key",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dc_003",
            "difficulty": "medium",
            "options": _opts(
                "Use a method appropriate to the type and purpose of the data",
                "Always use the same method for every dataset",
                "Collect data without defining the purpose",
                "Avoid documenting the collection process",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dc_004",
            "difficulty": "medium",
            "options": _opts(
                "A structured questionnaire",
                "A database backup",
                "A software license",
                "A network firewall",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dc_005",
            "difficulty": "hard",
            "options": _opts(
                "Select a collection method that balances validity, coverage, reliability, and feasibility",
                "Select the method that produces the largest number of records regardless of quality",
                "Use multiple collection methods without checking whether they measure the same thing",
                "Choose the fastest method even if it introduces systematic bias",
            ),
            "correct_option_id": "a",
        },
    ],

    # -----------------------------------------------------------------------
    # CC-0022: Data Validation
    # -----------------------------------------------------------------------

    "CC-0022": [
        {
            "id": "mcq_dv_001",
            "difficulty": "easy",
            "options": _opts(
                "Checking data against defined rules",
                "Deleting the entire dataset",
                "Encrypting every database column",
                "Changing the database password",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dv_002",
            "difficulty": "easy",
            "options": _opts(
                "Checking whether a required field is missing",
                "Changing a user's password",
                "Installing an operating system",
                "Creating a presentation",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dv_003",
            "difficulty": "medium",
            "options": _opts(
                "A date field contains a value that does not follow the expected date format",
                "A database has a valid primary key",
                "A report has a title",
                "A file has a valid extension",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dv_004",
            "difficulty": "medium",
            "options": _opts(
                "Range validation",
                "Password hashing",
                "File compression",
                "Network routing",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dv_005",
            "difficulty": "hard",
            "options": _opts(
                "Combine format, range, completeness, consistency, and domain-specific checks",
                "Only check whether every field contains some value",
                "Validate only the first few records",
                "Assume data is valid whenever it comes from an internal system",
            ),
            "correct_option_id": "a",
        },
    ],

    # -----------------------------------------------------------------------
    # CC-0026: Documentation on methodology
    # -----------------------------------------------------------------------

    "CC-0026": [
        {
            "id": "mcq_dm_001",
            "difficulty": "easy",
            "options": _opts(
                "A record explaining how data was collected and processed",
                "A database password",
                "A software installation file",
                "A network configuration",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dm_002",
            "difficulty": "easy",
            "options": _opts(
                "Documenting the methods used to produce the data",
                "Deleting the original data",
                "Changing the file extension",
                "Removing all metadata",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dm_003",
            "difficulty": "medium",
            "options": _opts(
                "Collection methods, definitions, processing steps, and relevant assumptions",
                "Only the name of the person who created the dataset",
                "Only the size of the database",
                "Only the date the report was printed",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dm_004",
            "difficulty": "medium",
            "options": _opts(
                "It improves reproducibility and helps users understand how results were produced",
                "It guarantees that the data contains no errors",
                "It removes the need for data validation",
                "It automatically increases the dataset size",
            ),
            "correct_option_id": "a",
        },
        {
            "id": "mcq_dm_005",
            "difficulty": "hard",
            "options": _opts(
                "Document methodological changes so users can understand differences across versions",
                "Overwrite all previous methodological information",
                "Record only the final result and omit processing details",
                "Avoid documenting changes because metadata should remain static",
            ),
            "correct_option_id": "a",
        },
    ],
}


# ---------------------------------------------------------------------------
# 6. VERIFY REAL CONCEPTS
# ---------------------------------------------------------------------------

def verify_real_concepts(db) -> None:
    """Ensure all required real concepts exist before seeding MCQs."""

    print("\n--- Checking real concepts ---")

    concepts = (
        db.query(ConceptTaxonomy)
        .filter(
            ConceptTaxonomy.canonical_concept_id.in_(
                BKT_TEST_CONCEPT_IDS
            )
        )
        .all()
    )

    found_ids = {
        concept.canonical_concept_id
        for concept in concepts
    }

    missing_ids = set(BKT_TEST_CONCEPT_IDS) - found_ids

    if missing_ids:
        raise RuntimeError(
            "Required real concepts are missing from concept_taxonomy: "
            + ", ".join(sorted(missing_ids))
        )

    for concept in concepts:
        print(
            f"[ok] {concept.canonical_concept_id} | "
            f"{concept.canonical_concept_name} | "
            f"competency_area={concept.competency_area} | "
            f"embedding={'yes' if concept.embedding is not None else 'NO'}"
        )

        if concept.embedding is None:
            raise RuntimeError(
                f"Concept {concept.canonical_concept_id} has no embedding."
            )


# ---------------------------------------------------------------------------
# 7. SEED EMPLOYEES
# ---------------------------------------------------------------------------

def seed_employees(db) -> None:
    print("\n--- Seeding test employees ---")

    for employee in TEST_EMPLOYEES:

        existing = (
            db.query(EmployeeProfile)
            .filter_by(employee_id=employee["employee_id"])
            .first()
        )

        if existing:
            print(
                f"[skip] employee_profile "
                f"{employee['employee_id']} already exists"
            )
            continue

        db.add(EmployeeProfile(**employee))

        print(
            f"[insert] employee_profile "
            f"{employee['employee_id']} "
            f"({employee['designation']})"
        )

    db.commit()


# ---------------------------------------------------------------------------
# 8. SEED COMPETENCY MATRIX
# ---------------------------------------------------------------------------

def seed_competency_matrix(db) -> None:
    print("\n--- Seeding competency framework matrix ---")

    for row in COMPETENCY_MATRIX_ROWS:

        exists = (
            db.query(CompetencyFrameworkMatrix)
            .filter_by(
                designation=row["designation"],
                competency_domain=row["competency_domain"],
            )
            .first()
        )

        if exists:
            print(
                f"[skip] competency matrix "
                f"({row['designation']}, "
                f"{row['competency_domain']}) already exists"
            )
            continue

        db.add(
            CompetencyFrameworkMatrix(**row)
        )

        print(
            f"[insert] competency matrix "
            f"({row['designation']}, "
            f"{row['competency_domain']}) "
            f"-> level {row['expected_proficiency_level']}"
        )

    db.commit()


# ---------------------------------------------------------------------------
# 9. SEED MCQs
# ---------------------------------------------------------------------------

def seed_mcqs(db) -> None:
    print("\n--- Seeding MCQs ---")

    for concept_id in BKT_TEST_CONCEPT_IDS:

        questions = MCQS_BY_CONCEPT.get(concept_id)

        if not questions:
            raise RuntimeError(
                f"No MCQs defined for real concept {concept_id}"
            )

        for question in questions:

            existing = (
                db.query(MCQ)
                .filter_by(id=question["id"])
                .first()
            )

            if existing:
                print(
                    f"[skip] MCQ {question['id']} already exists"
                )
                continue

            db.add(
                MCQ(
                    id=question["id"],
                    concept_id=concept_id,
                    options=question["options"],
                    correct_option_id=question["correct_option_id"],
                    difficulty=question["difficulty"],
                    status="live",
                    times_served=0,
                    times_correct=0,
                )
            )

            print(
                f"[insert] MCQ {question['id']} "
                f"(concept={concept_id}, "
                f"difficulty={question['difficulty']})"
            )

    db.commit()


# ---------------------------------------------------------------------------
# 10. VERIFY MCQ BANK HEALTH
# ---------------------------------------------------------------------------

def verify(db) -> None:
    print(
        "\n--- Bank health check "
        "(>=5 live MCQs and >=2 difficulty levels) ---"
    )

    all_healthy = True

    for concept_id in BKT_TEST_CONCEPT_IDS:

        rows = (
            db.query(MCQ.difficulty)
            .filter(
                MCQ.concept_id == concept_id,
                MCQ.status == "live",
            )
            .all()
        )

        difficulties = [row[0] for row in rows]
        distinct_difficulties = set(difficulties)

        healthy = (
            len(difficulties) >= 5
            and len(distinct_difficulties) >= 2
        )

        if not healthy:
            all_healthy = False

        status = "OK" if healthy else "FAIL"

        print(
            f"  {concept_id}: "
            f"total={len(difficulties)} "
            f"difficulties={sorted(distinct_difficulties)} "
            f"[{status}]"
        )

    if not all_healthy:
        raise RuntimeError(
            "One or more concepts failed the MCQ bank health check."
        )


# ---------------------------------------------------------------------------
# 11. MAIN
# ---------------------------------------------------------------------------

def main():

    db = SessionLocal()

    try:

        print("==============================================")
        print(" BKT TEST DATA SEED")
        print("==============================================")

        # Make sure the real taxonomy exists first.
        verify_real_concepts(db)

        # Seed test employees.
        seed_employees(db)

        # Seed competency mappings.
        seed_competency_matrix(db)

        # Seed MCQs for the three real concepts.
        seed_mcqs(db)

        # Verify the MCQ bank.
        verify(db)

        print("\n==============================================")
        print(" BKT TEST DATA SEED COMPLETED SUCCESSFULLY")
        print("==============================================")

    except Exception:
        db.rollback()
        raise

    finally:
        db.close()


if __name__ == "__main__":
    main()